"use strict";

// pages-build: permanent same-origin redirects for renamed or retired routes.
const SOURCE_PATTERN = /^\/[a-z0-9\-/]*\/$/u;
const DESTINATION_PATTERN = /^\/[a-z0-9._\-/]*(?:#[a-z][a-z0-9_-]*)?$/u;

function validateRedirects(data) {
  if (!data || typeof data !== "object" || !Array.isArray(data.redirects)) {
    throw new Error("Redirects file must be an object with a redirects array.");
  }
  const seen = new Set();
  return data.redirects.map((entry, index) => {
    const label = `redirects[${index}]`;
    if (typeof entry?.from !== "string" || !SOURCE_PATTERN.test(entry.from)) {
      throw new Error(`${label}.from must be a site page path ending in "/".`);
    }
    if (typeof entry?.to !== "string" || !DESTINATION_PATTERN.test(entry.to) || entry.to.startsWith("//")) {
      throw new Error(`${label}.to must be a same-origin site path with an optional fragment.`);
    }
    if (seen.has(entry.from)) throw new Error(`Duplicate redirect source ${entry.from}.`);
    seen.add(entry.from);
    if (typeof entry.reason !== "string" || entry.reason.trim() === "") {
      throw new Error(`${label}.reason is required.`);
    }
    const [toPath, fragment = ""] = entry.to.split("#");
    if (entry.from === toPath) throw new Error(`Redirect ${entry.from} cannot target itself.`);
    return { from: entry.from, to: entry.to, toPath, fragment, reason: entry.reason.trim() };
  });
}

function fragmentSetFor(generatedFragments, route) {
  if (generatedFragments instanceof Map) return generatedFragments.get(route) || new Set();
  return new Set(generatedFragments?.[route] || []);
}

function assertRedirectsConsistent({ redirects, generatedRoutes, generatedFragments = new Map() }) {
  const routes = new Set(generatedRoutes);
  const sources = new Set(redirects.map((redirect) => redirect.from));
  for (const redirect of redirects) {
    if (routes.has(redirect.from)) {
      throw new Error(`Redirect source ${redirect.from} is still a generated page; remove the redirect or the page.`);
    }
    if (sources.has(redirect.toPath)) {
      throw new Error(`Redirect chain or cycle detected: ${redirect.from} -> ${redirect.toPath}.`);
    }
    if (!routes.has(redirect.toPath)) {
      throw new Error(`Redirect ${redirect.from} -> ${redirect.to} points at a route the build does not generate.`);
    }
    if (redirect.fragment && !fragmentSetFor(generatedFragments, redirect.toPath).has(redirect.fragment)) {
      throw new Error(`Redirect ${redirect.from} -> ${redirect.to} points at missing fragment #${redirect.fragment}.`);
    }
  }
}

function renderRedirectsFile(redirects) {
  const lines = ["# Generated by scripts/build-pages.js from content/publication/redirects.json"];
  for (const redirect of redirects) {
    lines.push(`${redirect.from} ${redirect.to} 301`);
    lines.push(`${redirect.from.replace(/\/$/u, "")} ${redirect.to} 301`);
  }
  return `${lines.join("\n")}\n`;
}

module.exports = { assertRedirectsConsistent, renderRedirectsFile, validateRedirects };
