"use strict";

// pages-build: permanent redirects for renamed or retired routes, emitted as a
// Cloudflare static-assets `_redirects` file. Every source must be a route the build no
// longer generates and every destination must be a generated route, so a rename cannot
// leave old links pointing at a 404 and a redirect cannot shadow a live page.

const PATH_PATTERN = /^\/[a-z0-9\-/]*\/$/u;

function validateRedirects(data) {
  if (!data || typeof data !== "object" || !Array.isArray(data.redirects)) {
    throw new Error("Redirects file must be an object with a redirects array.");
  }
  const seen = new Set();
  return data.redirects.map((entry, index) => {
    const label = `redirects[${index}]`;
    for (const key of ["from", "to"]) {
      if (typeof entry?.[key] !== "string" || !PATH_PATTERN.test(entry[key])) {
        throw new Error(`${label}.${key} must be a site path ending in "/".`);
      }
    }
    if (seen.has(entry.from)) {
      throw new Error(`Duplicate redirect source ${entry.from}.`);
    }
    seen.add(entry.from);
    if (typeof entry.reason !== "string" || entry.reason.trim() === "") {
      throw new Error(`${label}.reason is required.`);
    }
    return { from: entry.from, to: entry.to, reason: entry.reason.trim() };
  });
}

function assertRedirectsConsistent({ redirects, generatedRoutes }) {
  const routes = new Set(generatedRoutes);
  for (const redirect of redirects) {
    if (routes.has(redirect.from)) {
      throw new Error(`Redirect source ${redirect.from} is still a generated page; remove the redirect or the page.`);
    }
    if (!routes.has(redirect.to)) {
      throw new Error(`Redirect ${redirect.from} -> ${redirect.to} points at a route the build does not generate.`);
    }
  }
}

function renderRedirectsFile(redirects) {
  const lines = ["# Generated by scripts/build-pages.js from content/publication/redirects.json"];
  for (const redirect of redirects) {
    lines.push(`${redirect.from} ${redirect.to} 301`);
    // Also match the path without its trailing slash.
    lines.push(`${redirect.from.replace(/\/$/u, "")} ${redirect.to} 301`);
  }
  return `${lines.join("\n")}\n`;
}

module.exports = {
  assertRedirectsConsistent,
  renderRedirectsFile,
  validateRedirects,
};
